spring:
  cloud:
    stream:
      rocketmq:
        bindings:
          input4:
            consumer:
              # 异步接收
#              orderly: false
              tags: tag2
          input3:
            consumer:
              # 同步顺序接收
              orderly: true
              tags: tag3
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input3: {group: "test-group3", destination: "test", content-type: "application/json"}
        input4: {group: "test-group4", content-type: "application/json", destination: "test"}


server:
  port: 9090
rocketmq:
  name-server: 127.0.0.1:9876